
FULLACCESSGMAILSCOPE = 'https://mail.google.com/'
LABELSGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.labels'
SENDGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.send'
READONLYGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.readonly'
COMPOSEGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.compose'
INSERTGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.insert'
MODIFYGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.modify'
METADATAGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.metadata'
SETTINGSBASICGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.settings.basic'
SETTINGSSHARINGGMAILSCOPE = 'https://www.googleapis.com/auth/gmail.settings.sharing'
