
FULLACCESSDRIVESCOPE = 'https://www.googleapis.com/auth/drive'
APPDATADRIVESCOPE = 'https://www.googleapis.com/auth/drive.appdata'
FILEDRIVESCOPE = 'https://www.googleapis.com/auth/drive.file'
INSTALLDRIVESCOPE = 'https://www.googleapis.com/auth/drive.install'
APPSREADONLYDRIVESCOPE = 'https://www.googleapis.com/auth/drive.apps.readonly'
METADATADRIVESCOPE = 'https://www.googleapis.com/auth/drive.metadata'
ACTIVITYDRIVESCOPE = 'https://www.googleapis.com/auth/drive.activity'
ACTIVITYREADONLYDRIVESCOPE = 'https://www.googleapis.com/auth/drive.activity.readonly'
READONLYDRIVESCOPE = 'https://www.googleapis.com/auth/drive.readonly'
METADATAREADONLYDRIVESCOPE = 'https://www.googleapis.com/auth/drive.metadata.readonly'
SCRIPTSDRIVESCOPE = 'https://www.googleapis.com/auth/drive.scripts'
